const BAD_REQUEST = 400;
const UNAUTHORIZED = 401;
const ACCESS_DENIED = 403;
const NOT_FOUND = 404;
const CONFLICT = 409;
const ERROR = 500;

module.exports = {
  BAD_REQUEST,
  UNAUTHORIZED,
  ACCESS_DENIED,
  NOT_FOUND,
  CONFLICT,
  ERROR,
};
